---
apiVersion: v1
kind: Pod
metadata:
  name: dov-bear
  labels:
    name: dov-bear
    dept: eng
spec:
   containers:
   - name: dov-bear-container
     image: chukmunnlee/dov-bear:v2
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 3000
     env:
      - name: INSTANCE_NAME
        value: k8s-dov-bears
  