---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
    dept: eng
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bgg-database-svc
  #BGG_DB_PASSWORD: changeit
---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  labels:
    name: bggapp-secret
type: Opaque
data:
  # echo -n changeit | baset64 -w0 -
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: bggapp-v1-deploy
  labels:
    name: bggapp-v1-deploy
spec:
  replicas: 1
  #strategy:
    #type: RollingUpdate
    #rollingUpdate:
      #maxSurge: 1
      #maxUnavailable: 0
      # maxSurge: 25%
      # maxUnavailable: 25%
  selector:
    matchLabels:
      name: bggapp-v1-po
  template:
    metadata:
      name: bggapp-v1-po
      labels:
        name: bggapp-v1-po
        dept: eng
        version: v1
    spec:
      containers:
      - name: bggapp-v1-container  
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        args:
        - --prefix
        - /v1
        envFrom:
        - configMapRef:
            name: bggapp-cm
        - secretRef:
            name: bggapp-secret
        ports:
        - containerPort: 3000
        #livenessProbe:
          #httpGet:
           # path: /healthz
           # port: 3000
           # scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-v1-svc
  labels:
    name: bggapp-v1-svc
spec:
  #type: ClusterIP
  selector:
    name: bggapp-v1-po
    version: v1
  ports:
  - port: 3000
    targetPort: 3000
